MODULE EQUATIONMOD
      REAL, DIMENSION(:), ALLOCATABLE :: B,X,JS
      REAL, DIMENSION(:, :), ALLOCATABLE :: A
END MODULE EQUATIONMOD


MODULE GREENMOD
    REAL:: U,G,PI,PI1,PI2,HB,UOG,FR
	REAL :: P1,RL,RD,RB
    INTEGER :: STAGE,MITER
    CHARACTER*30 NAME

    INTEGER:: MNKDB,MDIFF,MDFREE,MTROM
    INTEGER:: NFS(20)
    INTEGER:: ITTE
    REAL:: DMESH
    REAL:: XTR(100),ZTR(100),TAOX(100)
    INTEGER NTAO

    REAL:: NEWTON_RESIDU
    REAL:: AIJX20,AIJX30,AIJX40,AIJX50,AIJX60,AIJX70
    REAL:: HULL_WP(200,3),HULL_WP0(200,3),ZFAC
    integer:: MMESH,MGRID
    
!!CALLOCATED IN OFF
	INTEGER :: NBPOINT,NBBLOCK,NAPOINT,NABLOCK,NX,NZ,NBZ,RBALL,NTFY,NBPOINT1,NBPOINTP,NBBLOCKP,NBPOINTW,NBBLOCKW
	INTEGER :: NFPOINT,NFBLOCK
    INTEGER :: NBTPOINT,NBTBLOCK
	INTEGER :: NFX,NFY,NFX0,NFY0,NIT,NFXA,NFXF,NFX1
    INTEGER :: NODENUM
	REAL ::  DFX,DFY,AY1
    REAL :: SUA,DFF,DARL,DARB,SUA_I,DFF_I,SINK,TRI,CW,CW1,SINKL,TRIL
    REAL :: WPLAZ(500),WPLAX(500)
    INTEGER, DIMENSION(:) ::NWPLAZ(200)
    REAL :: WPLX(500),WPLY(500),WPLZ(500)
    DIMENSION MWAP(200),WZ0(500)
    INTEGER:: NZS
    INTEGER,DIMENSION(:):: MARKWAP(100)
    INTEGER:: NWAPL 
    REAL:: WFZ(200)
!!CALLOCATED IN OFFSETIN
    INTEGER :: NTP, NTPN, KP, NCOM,TPNTP
    REAL, DIMENSION(:), ALLOCATABLE :: DNODE,DCORZ
    REAL, DIMENSION(:, :), ALLOCATABLE :: CORD,VECN,VECN1,PCORD,CORD0,VECN0
    REAL, DIMENSION(:, :,:), ALLOCATABLE :: VE
    INTEGER, DIMENSION(:, :), ALLOCATABLE :: INE,INE1,IN,INPE
    INTEGER, DIMENSION(:), ALLOCATABLE :: PAN,NPL,IDS
    INTEGER:: ICORD(5000)
    REAL:: CORDO(500,9,3)
!!CALLOCATED IN COEFMATRIX
    REAL, DIMENSION(:), ALLOCATABLE :: PS,SUMHIJ,SUMHIJ2,DMIP,DMIE
    REAL, DIMENSION(:, :), ALLOCATABLE :: CORL,CNL
    REAL, DIMENSION(:), ALLOCATABLE :: DS,SSH,SSA,SSA1,SSH1
	REAL, DIMENSION(:), ALLOCATABLE :: HIJ,AIJ,HIJ1,AIJ1
    REAL, DIMENSION(:, :), ALLOCATABLE :: RSA,RSH1,RSA1,RFSA
    REAL, DIMENSION(:, :,:), ALLOCATABLE :: RSH
    REAL :: LOFFZ,LOFFX,LOFFY
    INTEGER NI
!!CALLOCATED IN MATRIX
	REAL, DIMENSION(:, :), ALLOCATABLE :: SH,SA,SA1
    REAL, DIMENSION(:, :), ALLOCATABLE :: SX,SZ,SY,SXX,SXY,SXZ,SYY,SYZ
	REAL, DIMENSION(:, :), ALLOCATABLE :: MAL,MAR,MAL1,MAL0
	REAL, DIMENSION(:), ALLOCATABLE :: VEL,VER,VERR,VERRI
	REAL, DIMENSION(:), ALLOCATABLE :: ETAW(:),ETAW0(:),ETAW1(:),PHIW(:),PHIW_N(:),PHIW_T(:) !INCIDENT POTENTIAL
    REAL, DIMENSION(:), ALLOCATABLE :: PHIS(:),PHIS_X(:),PHIS_Y(:),PHIS_Z(:),PHIS_N(:),&   !DISTURBANCE POTENTIAL
                                             PHIS_XX(:),PHIS_XY(:),PHIS_XZ(:),&
                                             PHIS_YX(:),PHIS_YY(:),PHIS_YZ(:),&
                                             PHIS_ZX(:),PHIS_ZY(:),PHIS_ZZ(:),&
                                             PHIS_XN(:),PHIS_YN(:),PHIS_ZN(:),ETAW_X(:),ETAW_Y(:),ETAW_T(:),TPREX(:)
    
    REAL, DIMENSION(:), ALLOCATABLE :: SIGM(:),SIGM0(:),SIGMI(:),SMPHI(:)
    REAL, DIMENSION(:), ALLOCATABLE :: DPHIS,DPHIS_X,DPHIS_Y,DPHIS_XX,DPHIS_XY,DPHIS_YY
!!CALLOCATED IN FREELATTICE
	REAL :: FZ
    REAL, DIMENSION(:,:), ALLOCATABLE :: FX
	REAL, DIMENSION(:,:), ALLOCATABLE :: FY
!!CUSED IN SURFACEWAVE
	REAL, DIMENSION(:), ALLOCATABLE :: SP,SV2,SF,SP2,VRIGHT
    REAL, DIMENSION(:), ALLOCATABLE :: SPN,SPX,SPY,SPZ,SPXX,SPXY,SPXZ,SPYY,SPYZ
    REAL, DIMENSION(:), ALLOCATABLE :: SPX0,SPY0,SPZ0,SPXX0,SPXY0,SPXZ0,SPYY0,SPYZ0,SP0
    REAL, DIMENSION(:), ALLOCATABLE :: SPX0N,SPY0N,SPZ0N,SPXX0N,SPXY0N,SPXZ0N,SPYY0N,SPYZ0N,SP0N
    REAL, DIMENSION(:), ALLOCATABLE :: SPX0N_1,SPY0N_1,SPZ0N_1,SPXX0N_1,SPXY0N_1,SPXZ0N_1,SPYY0N_1,SPYZ0N_1,SP0N_1
! ALLOCATED IN STATIC
    REAL ::WFA,VOL,XBUO(3),XGRA(3)
    REAL ::IXX,IYY,IZZ,IXY,IYZ,IXZ
    REAL ::LXX,LYY,LXY
    REAL ::XFA,YFA
    REAL ::SAREA,SAREA0
! ALLOCATED IN FIRWAVEF
    REAL ::NF(3),XMN(3),MX_I(6),MX(6),F1(6),FC(6),MA_I(12)
    REAL ::WF1(6,10),WF2(6,10),DF1(6),DF1_I(6),DF1_I1(6),WF3(6,6,20)
    REAL ::GMA(6)  !GENERALIZED ACCELERATION
! ALLOCATED IN CAMOTION
    REAL:: MASS(6,6),RESTO(6,6),MA(12),MY(12),MV_I(6),MV(6),FE(6),FM(6),MASS0(6,6)
! USED IN SOLID ANGLE
    REAL, DIMENSION(:), ALLOCATABLE :: SE 
! USED IN PADCOEF
    REAL,DIMENSION(:,:,:),ALLOCATABLE:: DPXC(:,:,:),DPYC(:,:,:),DPZC(:,:,:),DEXC(:,:,:),DEYC(:,:,:),DPNC(:,:,:)
    REAL,DIMENSION(:,:),ALLOCATABLE:: APX(:,:),APY(:,:),APZ(:,:),AEX(:,:),AEY(:,:),APEX(:,:),AENX(:,:),APN(:,:)
    INTEGER,DIMENSION(:,:,:),ALLOCATABLE:: DPM(:,:,:)
    REAL, DIMENSION(:), ALLOCATABLE :: RG

! ALLOCATED IN PARALLEL
    INTEGER NTHREAD
    INTEGER NPS(100),NBS(100),NPS1(100)    !线程数、每一线程的数据数目
    REAL, DIMENSION(:,:), ALLOCATABLE ::CI,APG,AG,WI,BV,BH
    REAL, DIMENSION(:), ALLOCATABLE ::BB,PG,QG,BNORM1,GG,YG,CG,SG
! ALLOCATED IN DIFF
    REAL,ALLOCATABLE ::DMX(:,:),DMY(:,:),DVMX(:,:),DVMY(:,:),DVALU(:,:)
    REAL,DIMENSION(:,:), ALLOCATABLE:: DCORD,ECORD
! USED IN GMRES
    REAL,ALLOCATABLE ::DAG(:,:),DDA(:,:),DA_1(:,:),X_BAR(:),BAX(:),RG0(:),JXD(:)
    REAL,ALLOCATABLE,TARGET ::LAG(:,:),UA(:,:)
    REAL*8,ALLOCATABLE ::LAGA(:),UAA(:)
    REAL:: TILU,TGMR
    
    INTEGER,ALLOCATABLE:: S_LN(:,:),S_UN(:,:),IALA(:),JALA(:),IAUA(:),JAUA(:) !,LEV(:,:)
    REAL,ALLOCATABLE:: NORMJ(:)
    REAL,ALLOCATABLE,TARGET:: ROW(:)

    CHARACTER*100:: ADDRESS,FOLDERNAME
    
    INTEGER:: XMDEN
    REAL:: SCALE2
    REAL:: BVEL(10000,3)
END MODULE GREENMOD

MODULE CUMOD
	!REAL :: U,G,PI,HB,UOG,FR
END MODULE CUMOD

MODULE FOLDERMOD
	!REAL :: U,G,PI,HB,UOG,FR
    CHARACTER*100:: ADDRESS1,FOLDERNAME1
END MODULE FOLDERMOD

MODULE NMLMOD
	INTEGER :: NML
END MODULE NMLMOD

MODULE INPUTDATA
    REAL:: NSWIN(20,50)
    REAL:: PANIN(20,6)
END MODULE
